LOCATION_FULLNAMES = {
    "ALB": "Aldeboarn",
    "ASD": "Assendelft",
    "ROU": "Rouveen",
    "VLI": "Vlist",
    "ZEG": "Zegveld",
    "DEM": "Demmerik",
    "LW": "LangeWeide",
    "VEG": "Vegelinsoord",
    "ZH": "ZegveldHoogwater",
    "LR": "LangRoggebroek",
    "GDA": "Gouda_MBORijnland",
    "BKW": "Berkenwoude",
    "BKG": "Bleskensgraaf",
    "CBW": "Cabauw",
    "HZW": "Hazerswoude-Dorp",
    "ROU09": "Rouveen_parcel09",
    "M4T": "Moordrecht-4eTochtweg",
    "MMW": "Moordrecht-Middelweg",
    "MSW": "Moordrecht-Spoorweglaan",
}

GROUNDWATER_WELLS = {
    "VLI RF": "VLI_RF_8",
    "ALB RF": "ALB_RF_7",
    "ASD RF": "ASD_RF_11",
    "ROU RF": "ROV_RF_11",
    "ZEG RF": "ZEG_RF16_10",
    "ZEG MP": "ZEG_MP16_2",
    "ZEG MS": "ZEG_MS16_17",
    "DEM": "DEM_NT_3",
    "LW": "LAW_MS_3",
    "VEG": "VEG_RF_2",
    "ZH": "ZEG_MP31_3",
    "GDA": "GDA_gwlevel",
    "BKW": "BKW_gwlevel",
    "BKG": "BKG_gwlevel",
    "CBW": "CBW_gwlevel",
    "HZW": "HZW_gwlevel",
    "ROU09 RF": "ROU09_gwlevel_RF",
    "ROU09 MS": "ROU09_gwlevel_MS",
    "MMW": "MMW_gwlevel",
    "M4T": "M4T_gwlevel",
    "MSW": "MSW_gwlevel",
}

SELECTED_GROUNDWATER_WELLS = {"ROU RF": ["ROV_RF_11", "ROV_MS_6", "ROV_MS_5"]}

HYDRAULIC_HEADS = {
    "ALB": "ALB_RF_9",
    "ASD": "ASD_MP_5",
    "ROU": "ROV_MS_6",
    "VLI": "VLI_RF_12",
    "ZEG": "",  # "ZEG_MS16_16",
    "DEM": "DEM_NT_6",
    "LW": "LAW_MS_6",
    "VEG": "VEG_RF_3",
    "ZH": "ZEG_MP31_6",
    "GDA": "GDA_hydraulic_head",
    "BKW": "BKW_hydraulic_head",
    "BKG": "BKG_hydraulic_head",
    "CBW": "CBW_hydraulic_head",
    "HZW": "HZW_hydraulic_head",
    "ROU09": "",
    "MMW": "MMW_hydraulic_head",
    "M4T": "M4T_hydraulic_head",
    "MSW": "MSW_hydraulic_head",
}

DITCHES = {
    "BKW": "BKW_ditch_level",
    "BKG": "BKG_ditch_level",
    "CBW": "CBW_ditch_level",
    "HZW": "HZW_ditch_level",
    "GDA": "GDA_ditch_level",
    "M4T": "M4T_ditch_level",
    "MSW": "MSW_ditch_level",
    "MMW": "MMW_ditch_level",
    "VEG": "VEG_OP_5",
    "ROU RF": "",
}

MIDDEPTH_FILTERS = {
    "ALB": "",
    "ASD": "ASD_MP_6",
    "ROU": "ROV_MS_5",
    "VLI": "VLI_RF_9",
    "ZEG": "ZEG_RF16_12",
    "DEM": "DEM_NT_5",
    "LW": "LAW_MS_5",
    "VEG": "",
    "ZH": "ZEG_MP31_5",
    "GDA": "",  # No middepth filter data available for Gouda
    "BKW": "",
    "BKG": "",
    "CBW": "",
    "HZW": "",
    "ROU09": "",
}

EXTENSOMETER_DEPTHS = {
    "ALB RF": [
        "0.06 m-mv",
        "0.40 m-mv",
        "0.80 m-mv",
        "1.21 m-mv",
        "2.10 m-mv",
        "7.40 m-mv",
    ],
    "ALB MS": [
        "0.06 m-mv",
        "0.40 m-mv",
        "0.81 m-mv",
        "1.20 m-mv",
        "2.10 m-mv",
        "8.20 m-mv",
    ],
    "ASD RF": [
        "0.06 m-mv",
        "0.33 m-mv",
        "0.79 m-mv",
        "1.21 m-mv",
        "1.90 m-mv",
        "16.80 m-mv",
    ],
    "ASD MP": [
        "0.06 m-mv",
        "0.34 m-mv",
        "0.81 m-mv",
        "1.22 m-mv",
        "1.99 m-mv",
        "16.80 m-mv",
    ],
    "ROU RF": ["0.05m-mv", "0.35m-mv", "1.15m-mv", "referentie 4.20m-mv"],
    "ROU MS": ["0.05m-mv", "0.35m-mv", "1.15m-mv", "referentie 4.20m-mv"],
    "VLI RF": [
        "0.05 m-mv",
        "0.37 m-mv",
        "0.78 m-mv",
        "1.20 m-mv",
        "6.85 m-mv",
        "15.30 m-mv",
    ],
    "VLI MS": [
        "0.05 m-mv",
        "0.39 m-mv",
        "0.79 m-mv",
        "1.18 m-mv",
        "6.74 m-mv",
        "15.20 m-mv",
    ],
    "ZEG RF": [
        "0.06 m-mv",
        "0.41 m-mv",
        "0.79 m-mv",
        "1.20 m-mv",
        "4.49 m-mv",
        "9.30 m-mv",
    ],
    "ZEG MP": [
        "0.07 m-mv",
        "0.42 m-mv",
        "0.80 m-mv",
        "1.21 m-mv",
        "4.21 m-mv",
        "9.20 m-mv",
    ],
    "ZEG MS": [
        "0.04 m-mv",
        "0.40 m-mv",
        "0.78 m-mv",
        "1.18 m-mv",
        "4.26 m-mv",
        "9.20 m-mv",
    ],
    "DEM": [
        "0.05 m-mv",
        "0.40 m-mv",
        "1.00 m-mv",
        "2.70 m-mv",
        "4.40 m-mv",
        "9.50 m-mv",
    ],
    "LW": [
        "0.06 m-mv",
        "0.45 m-mv",
        "0.80 m-mv",
        "1.20 m-mv",
        "3.50 m-mv",
        "12.30 m-mv",
    ],
    "VEG": ["0.04 m-mv", "0.29 m-mv", "9.40 m-mv"],
    "ZH": [
        "0.06 m-mv",
        "0.30 m-mv",
        "0.70 m-mv",
        "1.00 m-mv",
        "2.00 m-mv",
        "7.60 m-mv",
    ],
    "GDA": [
        "0.07 m-mv",
        "1.20 m-mv",
        "2.05 m-mv",
        "3.60 m-mv",
        "5.78 m-mv",
        "11.00 m-mv",
    ],
    "BKW": [
        "0.07 m-mv",
        "0.40 m-mv",
        "0.80 m-mv",
        "1.20 m-mv",
        "5.40 m-mv",
        "12.60 m-mv",
    ],
    "BKG": [
        "0.06 m-mv",
        "0.35 m-mv",
        "0.80 m-mv",
        "1.20 m-mv",
        "2.15 m-mv",
        "13.50 m-mv",
    ],
    "CBW": [
        "0.06 m-mv",
        "0.40 m-mv",
        "0.80 m-mv",
        "1.20 m-mv",
        "2.80 m-mv",
        "10.50 m-mv",
    ],
    "HZW": [
        "0.06 m-mv",
        "0.50 m-mv",
        "1.50 m-mv",
        "2.60 m-mv",
        "6.50 m-mv",
        "9.00 m-mv",
    ],
    "ROU09 RF": ["0.05m-mv", "1.15m-mv", "referentie 2.25m-mv"],
    "ROU09 MS": ["0.05m-mv", "1.15m-mv", "referentie 2.25m-mv"],
    "M4T": [
        "0.06 m-mv",
        "0.40 m-mv",
        "0.80 m-mv",
        "1.45 m-mv",
        "3.80 m-mv",
        "5.88 m-mv",
    ],
    "MMW": [
        "0.06 m-mv",
        "0.40 m-mv",
        "1.30 m-mv",
        "2.30 m-mv",
        "3.35 m-mv",
        "8.00 m-mv",
    ],
    "MSW": ["0.07 m-mv", "0.30 m-mv", "0.82 m-mv", "2.20 m-mv", "5.72 m-mv"],
}

SOILPROFILE_DEPTHS = {
    "ALB": 7.5,
    "ASD": 17.5,
    "ROU": 4.2,
    "ZEG": 9.3,
    "VLI": 15.3,
    "DEM": 9.5,
    "LW": 12.5,
    "VEG": 9.5,
    "ZH": 7.6,
    "GDA": 11.0,
    "BKW": 12.6,
    "BKG": 13.5,
    "CBW": 10.5,
    "HZW": 9.0,
    "ROU09": 2.25,
    "M4T": 6.20,
    "MMW": 8,
    "MSW": 7.85,
}

SOILTYPES_ENGLISH = {
    "veen, kleiig": "peat, clayey",
    "klei": "clay",
    "veen": "peat",
    "zand": "sand",
    "klei, humeus": "organic clay",
    "zand/leem": "sand/loam",
    "leem/zand": "loam/sand",
    "zand, gemixt met klei en/of silt": "sand, mixed \nwith clay and/or silt",
    "gyttja": "gyttja",
}

# code to invert a dictionary:
# inv_map = {v: k for k, v in my_map.items()}

SOILTYPES_DUTCH = {
    "peat, clayey": "veen, kleiig",
    "clay": "klei",
    "peat": "veen",
    "sand": "zand",
    "organic clay": "klei, humeus",
    "sand/loam": "zand/leem",
    "loam/sand": "leem/zand",
    "sand, mixed \nwith clay and/or silt": "zand, gemixt met klei en/of silt",
    "gyttja": "gyttja",
}

SOILTYPES_ENGLISH_REGIODEAL = {
    "K": "clay",
    "Z": "sand",
    "KH1": "organic clay",
    "KH2": "organic clay",
    "KH3": "organic clay",
    "ZH2": "organic sand",
    "ZH3": "organic sand",
    "V": "peat",
}

SOILTYPES_DUTCH_REGIODEAL = {
    "K": "klei",
    "Z": "zand",
    "KH1": "klei, humeus",
    "KH2": "klei, humeus",
    "KH3": "klei, humeus",
    "ZH2": "zand, humeus",
    "ZH3": "zand, humeus",
    "V": "veen",
}

SOILTYPES_COLORS = {
    "clay": "lawngreen",
    "organic clay": "yellowgreen",
    "peat": "sienna",
    "peat, clayey": "darkgoldenrod",
    "sand": "gold",
    "sand/loam": "orange",
    "organic sand": "darkkhaki",
    "loam/sand": "darkorange",
    "sand, mixed \nwith clay and/or silt": "burlywood",
    "gyttja": "#5C4033",
}

SOILTYPES_COLORS_DUTCH = {
    "klei": "lawngreen",
    "klei, humeus": "yellowgreen",
    "veen": "sienna",
    "veen, kleiig": "darkgoldenrod",
    "zand": "gold",
    "zand/leem": "orange",
    "zand, humeus": "darkkhaki",
    "leem/zand": "darkorange",
    "zand, gemixt met klei en/of silt": "burlywood",
    "gyttja": "#5C4033",
}

MONTHS = {
    1: "Januari",
    2: "Februari",
    3: "Maart",
    4: "April",
    5: "Mei",
    6: "Juni",
    7: "Juli",
    8: "Augustus",
    9: "September",
    10: "Oktober",
    11: "November",
    12: "December",
}
